package week9lab;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class RandomCharacterTest {
    private String randomCharacter;
    RandomCharacter randomChar = new RandomCharacter();

    @Test
    public void testLowerCaseLetter(){
        randomCharacter = randomChar.getRandomLowerCaseLetter();
        assertTrue(randomCharacter == randomCharacter.toLowerCase()); //Compare and check if both are the same
        //If it is the same, then return true
    }

    @Test
    public void testUpperCaseLetter(){
        randomCharacter = randomChar.getRandomUpperCaseLetter();
        assertTrue(randomCharacter == randomCharacter.toUpperCase()); //Compare and check if both are the same
        //If it is the same, then return true
    }

    @Test
    void testDigitCharacter() {
        randomCharacter = randomChar.getRandomDigitCharacter();
        int intRandomCharacter = Integer.parseInt(randomCharacter);
        assertTrue(0 <= intRandomCharacter && intRandomCharacter <= 9);
        //Check if the numerical value generated by the getRandomDigitCharacter() is within 0 and 9

    }

    @Test
    void testPrime() {
        randomCharacter = randomChar.getRandomDigitCharacter();
        boolean isPrime = true;
        int intRandomCharacter = Integer.parseInt(randomCharacter);
        System.out.println("The number generated to test for Prime is " + intRandomCharacter);
        if (intRandomCharacter <= 1){ //If value is less than or equals to 1, it is not a prime number
            isPrime = false;
        } else if (intRandomCharacter % 2 == 0 && intRandomCharacter != 2){
            //If the value is divisible by 2 and it is not 2
            isPrime = false;
        } else {
            isPrime = true;
        }
        assertTrue(isPrime); //If isPrime is false, the number is not prime and the test case will fail

    }
}